version: '3.5'

services:

  testing:
    build: .
    environment:
      TESTS_DIR: /qa_tools/qa_tool/tests
      ALLURE_DIR: /allure-results
      IS_LOCAL_START: 'true'
      JIRA_USER: ""
      JIRA_PASSWORD: ""
    image: qa-tool-testing
    volumes:
      - './allure-results:/allure-results'
    stdin_open: true
    tty: true
