version: '3.5'

services:

  testing:
    build: .
    environment:
      TESTS_DIR: /qa_tools/qa_tool/tests
      ALLURE_DIR: /allure-results
      SSH_PKEY_PATH: '/app/.ssh/id_rsa'
#      IS_LOCAL_START: 'true'
#      JIRA_USER: ""
#      JIRA_PASSWORD: ""
    image: qa-tool-testing
    volumes:
      - './allure-results:/allure-results'
      - '~/.ssh:/app/.ssh'
    stdin_open: true
    tty: true

  slack_bot:
    build: .
    user: "1005"
    environment:
      QA_CUSTOM_COMMAND: "python /qa_tools/services/slack_service.py"
      SLACK_TOKEN: "${SLACK_TOKEN}"
      PORTAINER_USER: "${PORTAINER_USER}"
      PORTAINER_PASSWORD: "${PORTAINER_PASSWORD}"
      PORTAINER_TTL_CACHE: 15
      SLACK_FOLDER_CONFIG: "/qa_tools/slack_cfg"
    volumes:
      - ./jenkins:/qa_tools/slack_cfg
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
