- scm:
    name: common_automation
    scm:
      - git:
          url: https://github.com/jibrelnetwork/jsearch-testing.git
          branches:
            - "*/$BRANCH_NAME"
          browser: githubweb
          browser-url: "https://github.com/jibrelnetwork/jsearch-testing"
          credentials-id: a8baf487-179a-4d46-8239-83a21945c810
          timeout: 20
          wipe-workspace: false
          clean:
            after: true
            before: true

- scm:
    name: jticker
    scm:
      - git:
          url: https://github.com/jibrelnetwork/jticker.git
          branches:
            - "*/${BRANCH_NAME_TEST}"
          browser: githubweb
          browser-url: "https://github.com/jibrelnetwork/jticker"
          credentials-id: a8baf487-179a-4d46-8239-83a21945c810
          timeout: 20
          wipe-workspace: false
          clean:
            after: true
            before: true
          submodule:
            disable: false
            recursive: true
            tracking: true
            parent-credentials: true



- wrapper:
    name: base
    wrappers:
      - timestamps
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
        - username-password-separated:
            credential-id: 9abe23df-63a8-4d1c-a3b6-93991a2a70a0
            name: GIT_USER
            password: GIT_PASSWORD
        - username-password-separated:
            credential-id: userpass-jibrelbot-dockerhub
            name: DOCKER_USER
            password: DOCKER_PASSWORD
        - username-password-separated:
            credential-id: 88d9eacc-29bc-4d98-a95c-e29664cde3c0
            name: JIRA_USER
            password: JIRA_PASSWORD
