- scm:
    name: common_automation
    scm:
      - git:
          url: https://github.com/jibrelnetwork/jsearch-testing.git
          branches:
            - "*/$BRANCH_NAME"
          browser: stash
          browser-url: "https://github.com/jibrelnetwork/jsearch-testing"
          credentials-id: a8baf487-179a-4d46-8239-83a21945c810
          timeout: 20
          per-build-tag: false
          skip-tag: true
          wipe-workspace: false
          clean:
            after: true
            before: true


- wrapper:
    name: base
    wrappers:
      - timestamps
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
        - text:
            credential-id: a8baf487-179a-4d46-8239-83a21945c810
            name: GIT_USER
            password: GIT_PASSWORD
