version: '3.7'

services:
  jenkins:
    environment:
      JENKINS_USER_ID: 1005
    user: 1005:999
    image: jenkinsci-docker_compose
    build:
      context: ../../
      dockerfile: ./deploy/jenkins/Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
      - 8443:443
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
