version: '3.7'

services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - 8080:8080
      - 50000:50000
      - 8443:443
    volumes:
      - /home/aleksandr/jenkins/jenkins_config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    user: '999'
